<?php

use App\Http\Controllers\Api\Legacy\LegacyDeprecationController;
use App\Http\Controllers\Api\V1\Admin\AiUsageLogController;
use App\Http\Controllers\Api\V1\Admin\BlogController as AdminBlogController;
use App\Http\Controllers\Api\V1\Admin\ApiIntegrationController;
use App\Http\Controllers\Api\V1\Admin\ApiProductController;
use App\Http\Controllers\Api\V1\Admin\ChatbotController;
use App\Http\Controllers\Api\V1\Admin\CorreoLogController;
use App\Http\Controllers\Api\V1\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Api\V1\Admin\MarketingDashboardController;
use App\Http\Controllers\Api\V1\Admin\MarketingPlanController;
use App\Http\Controllers\Api\V1\Admin\MarketingSubscriptionController;
use App\Http\Controllers\Api\V1\Admin\MercadoPagoSubscriptionPlanController;
use App\Http\Controllers\Api\V1\Admin\ProjectController;
use App\Http\Controllers\Api\V1\Admin\TaskController;
use App\Http\Controllers\Api\V1\Admin\UserController;
use App\Http\Controllers\Api\V1\Admin\UserIngresoController;
use App\Http\Controllers\Api\V1\Admin\UserMenuController;
use App\Http\Controllers\Api\V1\Admin\WebRequestController;
use App\Http\Controllers\Api\V1\Admin\WebsiteSubscriptionController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\Emprendedor\BlogController as EmprendedorBlogController;
use App\Http\Controllers\Api\V1\Emprendedor\ChatbotController as EmprendedorChatbotController;
use App\Http\Controllers\Api\V1\Emprendedor\ContractController as EmprendedorContractController;
use App\Http\Controllers\Api\V1\Emprendedor\DashboardController as EmprendedorDashboardController;
use App\Http\Controllers\Api\V1\Emprendedor\DefinicionController as EmprendedorDefinicionController;
use App\Http\Controllers\Api\V1\Emprendedor\MarketingController as EmprendedorMarketingController;
use App\Http\Controllers\Api\V1\Emprendedor\MenuController as EmprendedorMenuController;
use App\Http\Controllers\Api\V1\Emprendedor\MetricsController as EmprendedorMetricsController;
use App\Http\Controllers\Api\V1\Emprendedor\PaginaWebController as EmprendedorPaginaWebController;
use App\Http\Controllers\Api\V1\Emprendedor\ProductController as EmprendedorProductController;
use App\Http\Controllers\Api\V1\Emprendedor\WebsiteSubscriptionController as EmprendedorWebsiteSubscriptionController;
use App\Http\Controllers\Api\V1\Cliente\BlogController as ClienteBlogController;
use App\Http\Controllers\Api\V1\Cliente\ChatbotController as ClienteChatbotController;
use App\Http\Controllers\Api\V1\Cliente\ContractController as ClienteContractController;
use App\Http\Controllers\Api\V1\Cliente\DashboardController as ClienteDashboardController;
use App\Http\Controllers\Api\V1\Cliente\MarketingController as ClienteMarketingController;
use App\Http\Controllers\Api\V1\Cliente\MenuController as ClienteMenuController;
use App\Http\Controllers\Api\V1\Cliente\MetricsController as ClienteMetricsController;
use App\Http\Controllers\Api\V1\Cliente\ProductController as ClienteProductController;
use App\Http\Controllers\Api\V1\Marketing\DashboardController as MarketingUserDashboardController;
use App\Http\Controllers\Api\V1\Marketing\MenuController as MarketingUserMenuController;
use App\Http\Controllers\Api\V1\Marketing\MonitorController as MarketingUserMonitorController;
use App\Http\Controllers\Api\V1\Marketing\PlanController as MarketingUserPlanController;
use App\Http\Controllers\Api\V1\Marketing\ResultsController as MarketingUserResultsController;
use App\Http\Controllers\Api\V1\Marketing\SubscriptionController as MarketingUserSubscriptionController;
use App\Http\Controllers\Api\V1\Marketing\UsersController as MarketingUserUsersController;
use App\Http\Controllers\Api\V1\Webhooks\MercadoPagoWebhookController;
use App\Http\Middleware\HandlePublicApiCors;
use App\PublicEmbed\Controllers\Admin\ContactSubmissionController as AdminContactSubmissionController;
use App\PublicEmbed\Controllers\Panel\ContactSubmissionController as PanelContactSubmissionController;
use Illuminate\Support\Facades\Route;

Route::get('visit-tracker.js', [LegacyDeprecationController::class, 'deprecatedScript']);

Route::middleware([HandlePublicApiCors::class])->group(function (): void {
    Route::match(['POST', 'OPTIONS'], 'blog_api/index.php', [LegacyDeprecationController::class, 'gone']);
    Route::match(['POST', 'OPTIONS'], 'producto_api/index.php', [LegacyDeprecationController::class, 'gone']);
    Route::match(['POST', 'OPTIONS'], 'visit_user_page/index.php', [LegacyDeprecationController::class, 'gone']);
    Route::match(['POST', 'OPTIONS'], 'contact_form_landing_page/index.php', [LegacyDeprecationController::class, 'gone']);
});

Route::prefix('v1')->group(function (): void {
    Route::post('webhooks/mercadopago', [MercadoPagoWebhookController::class, 'handle']);

    Route::prefix('auth')->group(function (): void {
        Route::post('login', [AuthController::class, 'login']);
        Route::post('register', [AuthController::class, 'register']);
        Route::post('verify-email', [AuthController::class, 'verifyEmail']);
        Route::post('check-email', [AuthController::class, 'checkEmail']);

        Route::middleware('auth:sanctum')->group(function (): void {
            Route::get('me', [AuthController::class, 'me']);
            Route::post('logout', [AuthController::class, 'logout']);
        });
    });

    Route::middleware(['auth:sanctum', 'role:impulsa_administrador'])
        ->prefix('admin')
        ->group(function (): void {
            Route::get('dashboard/stats', [AdminDashboardController::class, 'stats']);
            Route::get('users', [UserController::class, 'index']);
            Route::post('users', [UserController::class, 'store']);
            Route::get('users/{user}', [UserController::class, 'show']);
            Route::put('users/{user}', [UserController::class, 'update']);
            Route::delete('users/{user}', [UserController::class, 'destroy']);
            Route::get('users/{user}/menu-options', [UserMenuController::class, 'options']);
            Route::put('users/{user}/menu', [UserMenuController::class, 'update']);
            Route::get('mail-logs', [CorreoLogController::class, 'index']);
            Route::get('mail-logs/{correoLog}', [CorreoLogController::class, 'show']);
            Route::post('mail-logs/{correoLog}/resend', [CorreoLogController::class, 'resend']);
            Route::get('ai-usage-logs/options', [AiUsageLogController::class, 'options']);
            Route::get('ai-usage-logs', [AiUsageLogController::class, 'index']);
            Route::get('ai-usage-logs/{aiUsageLog}', [AiUsageLogController::class, 'show']);
            Route::get('user-ingresos/options', [UserIngresoController::class, 'options']);
            Route::get('user-ingresos', [UserIngresoController::class, 'index']);
            Route::get('web-requests/internal', [WebRequestController::class, 'indexInternal']);
            Route::get('web-requests/internal/{webRequest}', [WebRequestController::class, 'showInternal']);
            Route::post('web-requests/internal/{webRequest}/create-project', [WebRequestController::class, 'createProjectFromInternal']);
            Route::get('web-requests/external', [WebRequestController::class, 'indexExternal']);
            Route::get('web-requests/external/{webRequest}', [WebRequestController::class, 'showExternal']);
            Route::post('web-requests/external/{webRequest}/create-user', [WebRequestController::class, 'createUserFromExternal']);
            Route::post('web-requests/external/{webRequest}/create-project', [WebRequestController::class, 'createProjectFromExternal']);
            Route::get('projects/options', [ProjectController::class, 'options']);
            Route::get('projects/managers', [ProjectController::class, 'managers']);
            Route::get('projects', [ProjectController::class, 'index']);
            Route::get('projects/{project}', [ProjectController::class, 'show']);
            Route::put('projects/{project}', [ProjectController::class, 'update']);
            Route::post('projects/{project}/phases', [ProjectController::class, 'storePhase']);
            Route::put('projects/{project}/phases/{phase}', [ProjectController::class, 'updatePhase']);
            Route::delete('projects/{project}/phases/{phase}', [ProjectController::class, 'destroyPhase']);
            Route::post('projects/{project}/deliverables', [ProjectController::class, 'storeDeliverable']);
            Route::put('projects/{project}/deliverables/{deliverable}', [ProjectController::class, 'updateDeliverable']);
            Route::delete('projects/{project}/deliverables/{deliverable}', [ProjectController::class, 'destroyDeliverable']);
            Route::get('projects/{project}/contract', [ProjectController::class, 'showContract']);
            Route::put('projects/{project}/contract', [ProjectController::class, 'updateContract']);
            Route::get('tasks/options', [TaskController::class, 'options']);
            Route::get('tasks/assignees', [TaskController::class, 'assignees']);
            Route::get('tasks', [TaskController::class, 'index']);
            Route::post('tasks', [TaskController::class, 'store']);
            Route::get('tasks/{adminTarea}', [TaskController::class, 'show']);
            Route::put('tasks/{adminTarea}', [TaskController::class, 'update']);
            Route::delete('tasks/{adminTarea}', [TaskController::class, 'destroy']);
            Route::get('api-integrations/options', [ApiIntegrationController::class, 'options']);
            Route::get('api-integrations/project-options', [ApiIntegrationController::class, 'projectOptions']);
            Route::get('api-integrations/owners', [ApiIntegrationController::class, 'owners']);
            Route::get('api-integrations/resolve-owner', [ApiIntegrationController::class, 'resolveOwner']);
            Route::get('api-integrations', [ApiIntegrationController::class, 'index']);
            Route::post('api-integrations', [ApiIntegrationController::class, 'store']);
            Route::get('api-integrations/{apiIntegration}', [ApiIntegrationController::class, 'show']);
            Route::put('api-integrations/{apiIntegration}', [ApiIntegrationController::class, 'update']);
            Route::post('api-integrations/{apiIntegration}/toggle-status', [ApiIntegrationController::class, 'toggleStatus']);
            Route::post('api-integrations/{apiIntegration}/regenerate-public-key', [ApiIntegrationController::class, 'regeneratePublicKey']);
            Route::post('api-integrations/{apiIntegration}/regenerate-secret-key', [ApiIntegrationController::class, 'regenerateSecretKey']);
            Route::get('contact-submissions', [AdminContactSubmissionController::class, 'index']);
            Route::get('contact-submissions/{contactSubmission}', [AdminContactSubmissionController::class, 'show']);
            Route::patch('contact-submissions/{contactSubmission}/state', [AdminContactSubmissionController::class, 'updateState']);
            Route::delete('contact-submissions/{contactSubmission}', [AdminContactSubmissionController::class, 'destroy']);
            Route::get('api-products/options', [ApiProductController::class, 'options']);
            Route::get('api-products/integration-options', [ApiProductController::class, 'integrationOptions']);
            Route::get('api-products/summary', [ApiProductController::class, 'summary']);
            Route::get('api-products/taxonomy', [ApiProductController::class, 'taxonomy']);
            Route::get('api-products', [ApiProductController::class, 'index']);
            Route::post('api-products', [ApiProductController::class, 'store']);
            Route::get('api-products/{apiProduct}', [ApiProductController::class, 'show']);
            Route::put('api-products/{apiProduct}', [ApiProductController::class, 'update']);
            Route::patch('api-products/{apiProduct}/status', [ApiProductController::class, 'updateStatus']);
            Route::delete('api-products/{apiProduct}', [ApiProductController::class, 'destroy']);
            Route::get('api-products/{apiProduct}/media/{mediaType}', [ApiProductController::class, 'media']);
            Route::get('blog/summary', [AdminBlogController::class, 'summary']);
            Route::get('blog', [AdminBlogController::class, 'index']);
            Route::get('blog/{postId}', [AdminBlogController::class, 'show']);
            Route::get('chatbots/summary', [ChatbotController::class, 'summary']);
            Route::get('chatbots/options', [ChatbotController::class, 'options']);
            Route::get('chatbots', [ChatbotController::class, 'index']);
            Route::get('chatbots/{chatbot}', [ChatbotController::class, 'show']);
            Route::patch('chatbots/{chatbot}/block', [ChatbotController::class, 'updateBlock']);
            Route::get('marketing/dashboard', [MarketingDashboardController::class, 'summary']);
            Route::get('marketing-plans/options', [MarketingPlanController::class, 'options']);
            Route::get('marketing-plans', [MarketingPlanController::class, 'index']);
            Route::post('marketing-plans', [MarketingPlanController::class, 'store']);
            Route::get('marketing-plans/{marketingPlan}', [MarketingPlanController::class, 'show']);
            Route::get('marketing-plans/{marketingPlan}/preview', [MarketingPlanController::class, 'preview']);
            Route::put('marketing-plans/{marketingPlan}', [MarketingPlanController::class, 'update']);
            Route::patch('marketing-plans/{marketingPlan}/status', [MarketingPlanController::class, 'updateStatus']);
            Route::get('marketing-subscriptions/options', [MarketingSubscriptionController::class, 'options']);
            Route::get('marketing-subscriptions', [MarketingSubscriptionController::class, 'index']);
            Route::get('marketing-subscriptions/{marketingPlanSubscription}', [MarketingSubscriptionController::class, 'show']);
            Route::patch('marketing-subscriptions/{marketingPlanSubscription}/status', [MarketingSubscriptionController::class, 'updateStatus']);
            Route::post('marketing-subscriptions/{marketingPlanSubscription}/mark-paid', [MarketingSubscriptionController::class, 'markPaid']);
            Route::get('website-subscriptions/options', [WebsiteSubscriptionController::class, 'options']);
            Route::get('website-subscriptions/integration-options', [WebsiteSubscriptionController::class, 'integrationOptions']);
            Route::get('website-subscriptions', [WebsiteSubscriptionController::class, 'index']);
            Route::post('website-subscriptions', [WebsiteSubscriptionController::class, 'store']);
            Route::get('website-subscriptions/{websiteSubscription}', [WebsiteSubscriptionController::class, 'show']);
            Route::put('website-subscriptions/{websiteSubscription}', [WebsiteSubscriptionController::class, 'update']);
            Route::put('website-subscriptions/{websiteSubscription}/periods/{period}', [WebsiteSubscriptionController::class, 'updatePeriod']);
            Route::post('website-subscriptions/{websiteSubscription}/periods/{period}/mark-paid', [WebsiteSubscriptionController::class, 'markPeriodPaid']);
            Route::get('mercadopago-subscription-plans/options', [MercadoPagoSubscriptionPlanController::class, 'options']);
            Route::get('mercadopago-subscription-plans', [MercadoPagoSubscriptionPlanController::class, 'index']);
            Route::post('mercadopago-subscription-plans', [MercadoPagoSubscriptionPlanController::class, 'store']);
            Route::get('mercadopago-subscription-plans/{mercadopagoSubscriptionPlan}', [MercadoPagoSubscriptionPlanController::class, 'show']);
            Route::put('mercadopago-subscription-plans/{mercadopagoSubscriptionPlan}', [MercadoPagoSubscriptionPlanController::class, 'update']);
            Route::post('mercadopago-subscription-plans/{mercadopagoSubscriptionPlan}/toggle-status', [MercadoPagoSubscriptionPlanController::class, 'toggleStatus']);
            Route::delete('mercadopago-subscription-plans/{mercadopagoSubscriptionPlan}', [MercadoPagoSubscriptionPlanController::class, 'destroy']);
        });

    Route::middleware(['auth:sanctum', 'role:impulsa_emprendedor'])
        ->prefix('emprendedor')
        ->group(function (): void {
            Route::get('menu', [EmprendedorMenuController::class, 'show']);
            Route::get('dashboard/stats', [EmprendedorDashboardController::class, 'stats']);
            Route::get('dashboard/projects/{projectId}/phases', [EmprendedorDashboardController::class, 'projectPhases']);
            Route::get('contracts/{contractId}', [EmprendedorContractController::class, 'show']);
            Route::post('contracts/{contractId}/sign', [EmprendedorContractController::class, 'sign']);
            Route::get('marketing/plans', [EmprendedorMarketingController::class, 'plans']);
            Route::get('marketing/plans/{planId}', [EmprendedorMarketingController::class, 'showPlan']);
            Route::get('marketing/subscriptions', [EmprendedorMarketingController::class, 'subscriptions']);
            Route::post('marketing/subscriptions', [EmprendedorMarketingController::class, 'storeSubscription']);
            Route::get('marketing/subscriptions/{marketingPlanSubscription}/payment-url', [EmprendedorMarketingController::class, 'paymentUrl']);
            Route::get('products/options', [EmprendedorProductController::class, 'options']);
            Route::get('products/summary', [EmprendedorProductController::class, 'summary']);
            Route::get('products/taxonomy', [EmprendedorProductController::class, 'taxonomy']);
            Route::get('products', [EmprendedorProductController::class, 'index']);
            Route::post('products', [EmprendedorProductController::class, 'store']);
            Route::get('products/{apiProduct}', [EmprendedorProductController::class, 'show']);
            Route::put('products/{apiProduct}', [EmprendedorProductController::class, 'update']);
            Route::patch('products/{apiProduct}/status', [EmprendedorProductController::class, 'updateStatus']);
            Route::delete('products/{apiProduct}', [EmprendedorProductController::class, 'destroy']);
            Route::get('products/{apiProduct}/media/{mediaType}', [EmprendedorProductController::class, 'media']);
            Route::get('chatbot', [EmprendedorChatbotController::class, 'show']);
            Route::get('chatbot/avatar', [EmprendedorChatbotController::class, 'avatar']);
            Route::put('chatbot/settings', [EmprendedorChatbotController::class, 'updateSettings']);
            Route::post('chatbot/settings', [EmprendedorChatbotController::class, 'updateSettings']);
            Route::patch('chatbot/status', [EmprendedorChatbotController::class, 'updateStatus']);
            Route::put('chatbot/nodes', [EmprendedorChatbotController::class, 'syncNodes']);
            Route::get('contact-submissions', [PanelContactSubmissionController::class, 'index']);
            Route::get('contact-submissions/{contactSubmission}', [PanelContactSubmissionController::class, 'show']);
            Route::patch('contact-submissions/{contactSubmission}/state', [PanelContactSubmissionController::class, 'updateState']);
            Route::delete('contact-submissions/{contactSubmission}', [PanelContactSubmissionController::class, 'destroy']);
            Route::get('website-subscription', [EmprendedorWebsiteSubscriptionController::class, 'show']);
            Route::get('pagina-web/overview', [EmprendedorPaginaWebController::class, 'overview']);
            Route::get('definicion', [EmprendedorDefinicionController::class, 'show']);
            Route::put('definicion/buyer-persona', [EmprendedorDefinicionController::class, 'saveBuyerPersona']);
            Route::put('definicion/mision', [EmprendedorDefinicionController::class, 'saveMision']);
            Route::put('definicion/vision', [EmprendedorDefinicionController::class, 'saveVision']);
            Route::put('definicion/landing', [EmprendedorDefinicionController::class, 'saveLanding']);
            Route::post('definicion/generate-estructura', [EmprendedorDefinicionController::class, 'generateEstructura'])
                ->middleware('throttle:10,1');
            Route::get('metrics/summary', [EmprendedorMetricsController::class, 'summary']);
            Route::get('metrics/dashboard', [EmprendedorMetricsController::class, 'dashboard']);
            Route::get('blog/taxonomy', [EmprendedorBlogController::class, 'taxonomy']);
            Route::get('blog', [EmprendedorBlogController::class, 'index']);
            Route::post('blog', [EmprendedorBlogController::class, 'store']);
            Route::get('blog/{postId}', [EmprendedorBlogController::class, 'show']);
            Route::put('blog/{postId}', [EmprendedorBlogController::class, 'update']);
            Route::patch('blog/{postId}/status', [EmprendedorBlogController::class, 'updateStatus']);
            Route::get('blog/{postId}/media/{mediaType}', [EmprendedorBlogController::class, 'media']);
            Route::delete('blog/{postId}', [EmprendedorBlogController::class, 'destroy']);
        });

    Route::middleware(['auth:sanctum', 'role:impulsa_cliente'])
        ->prefix('cliente')
        ->group(function (): void {
            Route::get('menu', [ClienteMenuController::class, 'show']);
            Route::get('dashboard/stats', [ClienteDashboardController::class, 'stats']);
            Route::get('contracts/{contractId}', [ClienteContractController::class, 'show']);
            Route::post('contracts/{contractId}/sign', [ClienteContractController::class, 'sign']);
            Route::get('marketing/plans', [ClienteMarketingController::class, 'plans']);
            Route::get('marketing/plans/{planId}', [ClienteMarketingController::class, 'showPlan']);
            Route::get('marketing/subscriptions', [ClienteMarketingController::class, 'subscriptions']);
            Route::post('marketing/subscriptions', [ClienteMarketingController::class, 'storeSubscription']);
            Route::get('marketing/subscriptions/{marketingPlanSubscription}/payment-url', [ClienteMarketingController::class, 'paymentUrl']);
            Route::get('products/options', [ClienteProductController::class, 'options']);
            Route::get('products/summary', [ClienteProductController::class, 'summary']);
            Route::get('products/taxonomy', [ClienteProductController::class, 'taxonomy']);
            Route::get('products', [ClienteProductController::class, 'index']);
            Route::post('products', [ClienteProductController::class, 'store']);
            Route::get('products/{apiProduct}', [ClienteProductController::class, 'show']);
            Route::put('products/{apiProduct}', [ClienteProductController::class, 'update']);
            Route::patch('products/{apiProduct}/status', [ClienteProductController::class, 'updateStatus']);
            Route::delete('products/{apiProduct}', [ClienteProductController::class, 'destroy']);
            Route::get('products/{apiProduct}/media/{mediaType}', [ClienteProductController::class, 'media']);
            Route::get('chatbot', [ClienteChatbotController::class, 'show']);
            Route::get('chatbot/avatar', [ClienteChatbotController::class, 'avatar']);
            Route::put('chatbot/settings', [ClienteChatbotController::class, 'updateSettings']);
            Route::post('chatbot/settings', [ClienteChatbotController::class, 'updateSettings']);
            Route::patch('chatbot/status', [ClienteChatbotController::class, 'updateStatus']);
            Route::put('chatbot/nodes', [ClienteChatbotController::class, 'syncNodes']);
            Route::get('contact-submissions', [PanelContactSubmissionController::class, 'index']);
            Route::get('contact-submissions/{contactSubmission}', [PanelContactSubmissionController::class, 'show']);
            Route::patch('contact-submissions/{contactSubmission}/state', [PanelContactSubmissionController::class, 'updateState']);
            Route::delete('contact-submissions/{contactSubmission}', [PanelContactSubmissionController::class, 'destroy']);
            Route::get('metrics/summary', [ClienteMetricsController::class, 'summary']);
            Route::get('metrics/dashboard', [ClienteMetricsController::class, 'dashboard']);
            Route::get('blog/taxonomy', [ClienteBlogController::class, 'taxonomy']);
            Route::get('blog', [ClienteBlogController::class, 'index']);
            Route::post('blog', [ClienteBlogController::class, 'store']);
            Route::get('blog/{postId}', [ClienteBlogController::class, 'show']);
            Route::put('blog/{postId}', [ClienteBlogController::class, 'update']);
            Route::patch('blog/{postId}/status', [ClienteBlogController::class, 'updateStatus']);
            Route::get('blog/{postId}/media/{mediaType}', [ClienteBlogController::class, 'media']);
            Route::delete('blog/{postId}', [ClienteBlogController::class, 'destroy']);
        });

    Route::middleware(['auth:sanctum', 'role:impulsa_marketing'])
        ->prefix('marketing-user')
        ->group(function (): void {
            Route::get('menu', [MarketingUserMenuController::class, 'show']);
            Route::get('dashboard', [MarketingUserDashboardController::class, 'summary']);
            Route::get('marketing-plans/options', [MarketingUserPlanController::class, 'options']);
            Route::get('marketing-plans', [MarketingUserPlanController::class, 'index']);
            Route::post('marketing-plans', [MarketingUserPlanController::class, 'store']);
            Route::get('marketing-plans/{marketingPlan}', [MarketingUserPlanController::class, 'show']);
            Route::get('marketing-plans/{marketingPlan}/preview', [MarketingUserPlanController::class, 'preview']);
            Route::put('marketing-plans/{marketingPlan}', [MarketingUserPlanController::class, 'update']);
            Route::patch('marketing-plans/{marketingPlan}/status', [MarketingUserPlanController::class, 'updateStatus']);
            Route::get('marketing-subscriptions/options', [MarketingUserSubscriptionController::class, 'options']);
            Route::get('marketing-subscriptions', [MarketingUserSubscriptionController::class, 'index']);
            Route::get('marketing-subscriptions/{marketingPlanSubscription}', [MarketingUserSubscriptionController::class, 'show']);
            Route::patch('marketing-subscriptions/{marketingPlanSubscription}/status', [MarketingUserSubscriptionController::class, 'updateStatus']);
            Route::post('marketing-subscriptions/{marketingPlanSubscription}/mark-paid', [MarketingUserSubscriptionController::class, 'markPaid']);
            Route::get('monitor/campaigns', [MarketingUserMonitorController::class, 'campaigns']);
            Route::post('monitor/import-csv', [MarketingUserMonitorController::class, 'importCsv']);
            Route::get('results', [MarketingUserResultsController::class, 'index']);
            Route::get('users', [MarketingUserUsersController::class, 'index']);
        });
});
