<?php

use App\Http\Controllers\Api\Legacy\LegacyDeprecationController;
use App\Http\Controllers\Api\V1\Admin\AcademiaController as AdminAcademiaController;
use App\Http\Controllers\Api\V1\Admin\AiUsageLogController;
use App\Http\Controllers\Api\V1\Admin\BlogController as AdminBlogController;
use App\Http\Controllers\Api\V1\Admin\ApiIntegrationController;
use App\Http\Controllers\Api\V1\Admin\ApiProductController;
use App\Http\Controllers\Api\V1\Admin\ChatbotController;
use App\Http\Controllers\Api\V1\Admin\EmailMarketingContactsController;
use App\Http\Controllers\Api\V1\Admin\CorreoLogController;
use App\Http\Controllers\Api\V1\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Api\V1\Admin\GoalsMonitorController;
use App\Http\Controllers\Api\V1\Admin\MarketingDashboardController;
use App\Http\Controllers\Api\V1\Admin\MarketingPlanController;
use App\Http\Controllers\Api\V1\Admin\MarketingSubscriptionController;
use App\Http\Controllers\Api\V1\Admin\MercadoPagoSubscriptionPlanController;
use App\Http\Controllers\Api\V1\Admin\ProjectController;
use App\Http\Controllers\Api\V1\Admin\TaskController;
use App\Http\Controllers\Api\V1\Admin\UserController;
use App\Http\Controllers\Api\V1\Admin\UserIngresoController;
use App\Http\Controllers\Api\V1\Admin\UserMenuController;
use App\Http\Controllers\Api\V1\Admin\WebRequestController;
use App\Http\Controllers\Api\V1\Admin\WebsiteSubscriptionController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\ProfileController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\Emprendedor\AcademiaController as EmprendedorAcademiaController;
use App\Http\Controllers\Api\V1\Emprendedor\BlogController as EmprendedorBlogController;
use App\Http\Controllers\Api\V1\Emprendedor\ChatbotController as EmprendedorChatbotController;
use App\Http\Controllers\Api\V1\Emprendedor\ContractController as EmprendedorContractController;
use App\Http\Controllers\Api\V1\Emprendedor\DashboardController as EmprendedorDashboardController;
use App\Http\Controllers\Api\V1\Emprendedor\DefinicionController as EmprendedorDefinicionController;
use App\Http\Controllers\Api\V1\Emprendedor\MarketingController as EmprendedorMarketingController;
use App\Http\Controllers\Api\V1\Emprendedor\MenuController as EmprendedorMenuController;
use App\Http\Controllers\Api\V1\Emprendedor\MetricsController as EmprendedorMetricsController;
use App\Http\Controllers\Api\V1\Emprendedor\PaginaWebController as EmprendedorPaginaWebController;
use App\Http\Controllers\Api\V1\Emprendedor\FinanzasController as EmprendedorFinanzasController;
use App\Http\Controllers\Api\V1\Emprendedor\GoalsController as EmprendedorGoalsController;
use App\Http\Controllers\Api\V1\Emprendedor\ProductController as EmprendedorProductController;
use App\Http\Controllers\Api\V1\Emprendedor\WebsiteSubscriptionController as EmprendedorWebsiteSubscriptionController;
use App\Http\Controllers\Api\V1\Cliente\AcademiaController as ClienteAcademiaController;
use App\Http\Controllers\Api\V1\Cliente\BlogController as ClienteBlogController;
use App\Http\Controllers\Api\V1\Cliente\ChatbotController as ClienteChatbotController;
use App\Http\Controllers\Api\V1\Cliente\ContractController as ClienteContractController;
use App\Http\Controllers\Api\V1\Cliente\DashboardController as ClienteDashboardController;
use App\Http\Controllers\Api\V1\Cliente\FinanzasController as ClienteFinanzasController;
use App\Http\Controllers\Api\V1\Cliente\GoalsController as ClienteGoalsController;
use App\Http\Controllers\Api\V1\Cliente\MarketingController as ClienteMarketingController;
use App\Http\Controllers\Api\V1\Cliente\MenuController as ClienteMenuController;
use App\Http\Controllers\Api\V1\Cliente\MetricsController as ClienteMetricsController;
use App\Http\Controllers\Api\V1\Cliente\ProductController as ClienteProductController;
use App\Http\Controllers\Api\V1\Colaborador\MenuController as ColaboradorMenuController;
use App\Http\Controllers\Api\V1\Colaborador\ProjectController as ColaboradorProjectController;
use App\Http\Controllers\Api\V1\Marketing\DashboardController as MarketingUserDashboardController;
use App\Http\Controllers\Api\V1\Marketing\MenuController as MarketingUserMenuController;
use App\Http\Controllers\Api\V1\Marketing\MonitorController as MarketingUserMonitorController;
use App\Http\Controllers\Api\V1\Marketing\PlanController as MarketingUserPlanController;
use App\Http\Controllers\Api\V1\Marketing\ResultsController as MarketingUserResultsController;
use App\Http\Controllers\Api\V1\Marketing\SubscriptionController as MarketingUserSubscriptionController;
use App\Http\Controllers\Api\V1\Marketing\UsersController as MarketingUserUsersController;
use App\Http\Controllers\Api\V1\Webhooks\MercadoPagoWebhookController;
use App\Http\Middleware\HandlePublicApiCors;
use App\PublicEmbed\Controllers\Admin\ContactSubmissionController as AdminContactSubmissionController;
use App\PublicEmbed\Controllers\Panel\ContactSubmissionController as PanelContactSubmissionController;
use Illuminate\Support\Facades\Route;

Route::get('visit-tracker.js', [LegacyDeprecationController::class, 'deprecatedScript']);

Route::middleware([HandlePublicApiCors::class])->group(function (): void {
    Route::match(['POST', 'OPTIONS'], 'blog_api/index.php', [LegacyDeprecationController::class, 'gone']);
    Route::match(['POST', 'OPTIONS'], 'producto_api/index.php', [LegacyDeprecationController::class, 'gone']);
    Route::match(['POST', 'OPTIONS'], 'visit_user_page/index.php', [LegacyDeprecationController::class, 'gone']);
    Route::match(['POST', 'OPTIONS'], 'contact_form_landing_page/index.php', [LegacyDeprecationController::class, 'gone']);
});

Route::prefix('v1')->group(function (): void {
    Route::post('webhooks/mercadopago', [MercadoPagoWebhookController::class, 'handle']);

    Route::prefix('auth')->group(function (): void {
        Route::post('login', [AuthController::class, 'login']);
        Route::post('register', [AuthController::class, 'register']);
        Route::post('verify-email', [AuthController::class, 'verifyEmail']);
        Route::post('check-email', [AuthController::class, 'checkEmail']);
        Route::post('forgot-password', [AuthController::class, 'forgotPassword'])->middleware('throttle:3,15');
        Route::post('reset-password', [AuthController::class, 'resetPassword'])->middleware('throttle:10,1');

        Route::middleware('auth:sanctum')->group(function (): void {
            Route::get('me', [AuthController::class, 'me']);
            Route::post('logout', [AuthController::class, 'logout']);
            Route::get('profile', [ProfileController::class, 'show']);
            Route::match(['PUT', 'POST'], 'profile', [ProfileController::class, 'update']);
            Route::get('profile/avatar', [ProfileController::class, 'avatar']);
        });
    });

    Route::middleware('auth:sanctum')->group(function (): void {
        Route::get('notifications', [NotificationController::class, 'index']);
        Route::get('notifications/unread-count', [NotificationController::class, 'unreadCount']);
        Route::post('notifications/read-all', [NotificationController::class, 'markAllRead']);
        Route::patch('notifications/{notification}/read', [NotificationController::class, 'markRead']);
        Route::delete('notifications/{notification}', [NotificationController::class, 'dismiss']);
    });

    Route::middleware(['auth:sanctum', 'role:impulsa_administrador'])
        ->prefix('admin')
        ->group(function (): void {
            Route::get('dashboard/stats', [AdminDashboardController::class, 'stats']);
            Route::get('users', [UserController::class, 'index']);
            Route::post('users', [UserController::class, 'store']);
            Route::get('users/{user}', [UserController::class, 'show']);
            Route::put('users/{user}', [UserController::class, 'update']);
            Route::delete('users/{user}', [UserController::class, 'destroy']);
            Route::get('users/{user}/menu-options', [UserMenuController::class, 'options']);
            Route::put('users/{user}/menu', [UserMenuController::class, 'update']);
            Route::get('mail-logs', [CorreoLogController::class, 'index']);
            Route::get('mail-logs/{correoLog}', [CorreoLogController::class, 'show']);
            Route::post('mail-logs/{correoLog}/resend', [CorreoLogController::class, 'resend']);
            Route::get('email-marketing/contacts', [EmailMarketingContactsController::class, 'index']);
            Route::get('email-marketing/contacts/export', [EmailMarketingContactsController::class, 'export']);
            Route::get('ai-usage-logs/options', [AiUsageLogController::class, 'options']);
            Route::get('ai-usage-logs', [AiUsageLogController::class, 'index']);
            Route::get('ai-usage-logs/{aiUsageLog}', [AiUsageLogController::class, 'show']);
            Route::get('metas/summary', [GoalsMonitorController::class, 'summary']);
            Route::get('metas/options', [GoalsMonitorController::class, 'options']);
            Route::get('metas', [GoalsMonitorController::class, 'index']);
            Route::get('metas/{goalId}', [GoalsMonitorController::class, 'show']);
            Route::get('user-ingresos/options', [UserIngresoController::class, 'options']);
            Route::get('user-ingresos', [UserIngresoController::class, 'index']);
            Route::get('web-requests/internal', [WebRequestController::class, 'indexInternal']);
            Route::get('web-requests/internal/{webRequest}', [WebRequestController::class, 'showInternal']);
            Route::post('web-requests/internal/{webRequest}/create-project', [WebRequestController::class, 'createProjectFromInternal']);
            Route::get('web-requests/external', [WebRequestController::class, 'indexExternal']);
            Route::get('web-requests/external/{webRequest}', [WebRequestController::class, 'showExternal']);
            Route::post('web-requests/external/{webRequest}/create-user', [WebRequestController::class, 'createUserFromExternal']);
            Route::post('web-requests/external/{webRequest}/create-project', [WebRequestController::class, 'createProjectFromExternal']);
            Route::get('projects/options', [ProjectController::class, 'options']);
            Route::get('projects/managers', [ProjectController::class, 'managers']);
            Route::get('projects/collaborators', [ProjectController::class, 'collaborators']);
            Route::get('projects/clients', [ProjectController::class, 'clients']);
            Route::get('projects', [ProjectController::class, 'index']);
            Route::post('projects', [ProjectController::class, 'store']);
            Route::get('projects/{project}', [ProjectController::class, 'show']);
            Route::put('projects/{project}', [ProjectController::class, 'update']);
            Route::post('projects/{project}/phases', [ProjectController::class, 'storePhase']);
            Route::put('projects/{project}/phases/{phase}', [ProjectController::class, 'updatePhase']);
            Route::delete('projects/{project}/phases/{phase}', [ProjectController::class, 'destroyPhase']);
            Route::post('projects/{project}/deliverables', [ProjectController::class, 'storeDeliverable']);
            Route::put('projects/{project}/deliverables/{deliverable}', [ProjectController::class, 'updateDeliverable']);
            Route::delete('projects/{project}/deliverables/{deliverable}', [ProjectController::class, 'destroyDeliverable']);
            Route::get('projects/{project}/comments', [ProjectController::class, 'projectComments']);
            Route::get('projects/{project}/deliverables/{deliverable}/comments', [ProjectController::class, 'deliverableComments']);
            Route::post('projects/{project}/deliverables/{deliverable}/comments', [ProjectController::class, 'storeDeliverableComment']);
            Route::post('projects/{project}/deliverables/{deliverable}/comments/read', [ProjectController::class, 'markDeliverableCommentsRead']);
            Route::post('projects/{project}/phases/{phase}/attachments', [ProjectController::class, 'storePhaseAttachment']);
            Route::post('projects/{project}/deliverables/{deliverable}/attachments', [ProjectController::class, 'storeDeliverableAttachment']);
            Route::get('projects/{project}/attachments/{attachment}/file', [ProjectController::class, 'showAttachment']);
            Route::delete('projects/{project}/attachments/{attachment}', [ProjectController::class, 'destroyAttachment']);
            Route::get('projects/{project}/contract', [ProjectController::class, 'showContract']);
            Route::put('projects/{project}/contract', [ProjectController::class, 'updateContract']);
            Route::post('projects/{project}/client-notification', [ProjectController::class, 'flushClientNotification']);
            Route::delete('projects/{project}/client-notification', [ProjectController::class, 'discardClientNotification']);
            Route::get('tasks/options', [TaskController::class, 'options']);
            Route::get('tasks/assignees', [TaskController::class, 'assignees']);
            Route::get('tasks', [TaskController::class, 'index']);
            Route::post('tasks', [TaskController::class, 'store']);
            Route::get('tasks/{adminTarea}', [TaskController::class, 'show']);
            Route::put('tasks/{adminTarea}', [TaskController::class, 'update']);
            Route::delete('tasks/{adminTarea}', [TaskController::class, 'destroy']);
            Route::get('api-integrations/options', [ApiIntegrationController::class, 'options']);
            Route::get('api-integrations/project-options', [ApiIntegrationController::class, 'projectOptions']);
            Route::get('api-integrations/owners', [ApiIntegrationController::class, 'owners']);
            Route::get('api-integrations/resolve-owner', [ApiIntegrationController::class, 'resolveOwner']);
            Route::get('api-integrations', [ApiIntegrationController::class, 'index']);
            Route::post('api-integrations', [ApiIntegrationController::class, 'store']);
            Route::get('api-integrations/{apiIntegration}', [ApiIntegrationController::class, 'show']);
            Route::put('api-integrations/{apiIntegration}', [ApiIntegrationController::class, 'update']);
            Route::post('api-integrations/{apiIntegration}/toggle-status', [ApiIntegrationController::class, 'toggleStatus']);
            Route::post('api-integrations/{apiIntegration}/regenerate-public-key', [ApiIntegrationController::class, 'regeneratePublicKey']);
            Route::post('api-integrations/{apiIntegration}/regenerate-secret-key', [ApiIntegrationController::class, 'regenerateSecretKey']);
            Route::get('contact-submissions', [AdminContactSubmissionController::class, 'index']);
            Route::get('contact-submissions/{contactSubmission}', [AdminContactSubmissionController::class, 'show']);
            Route::patch('contact-submissions/{contactSubmission}/state', [AdminContactSubmissionController::class, 'updateState']);
            Route::delete('contact-submissions/{contactSubmission}', [AdminContactSubmissionController::class, 'destroy']);
            Route::get('api-products/options', [ApiProductController::class, 'options']);
            Route::get('api-products/integration-options', [ApiProductController::class, 'integrationOptions']);
            Route::get('api-products/summary', [ApiProductController::class, 'summary']);
            Route::get('api-products/taxonomy', [ApiProductController::class, 'taxonomy']);
            Route::get('api-products', [ApiProductController::class, 'index']);
            Route::post('api-products', [ApiProductController::class, 'store']);
            Route::get('api-products/{apiProduct}', [ApiProductController::class, 'show']);
            Route::put('api-products/{apiProduct}', [ApiProductController::class, 'update']);
            Route::patch('api-products/{apiProduct}/status', [ApiProductController::class, 'updateStatus']);
            Route::delete('api-products/{apiProduct}', [ApiProductController::class, 'destroy']);
            Route::get('api-products/{apiProduct}/media/{mediaType}', [ApiProductController::class, 'media']);
            Route::get('academia/summary', [AdminAcademiaController::class, 'summary']);
            Route::get('academia/options', [AdminAcademiaController::class, 'options']);
            Route::get('academia/taxonomy', [AdminAcademiaController::class, 'taxonomy']);
            Route::get('academia', [AdminAcademiaController::class, 'index']);
            Route::post('academia', [AdminAcademiaController::class, 'store']);
            Route::get('academia/{academiaVideo}', [AdminAcademiaController::class, 'show']);
            Route::put('academia/{academiaVideo}', [AdminAcademiaController::class, 'update']);
            Route::patch('academia/{academiaVideo}/status', [AdminAcademiaController::class, 'updateStatus']);
            Route::delete('academia/{academiaVideo}', [AdminAcademiaController::class, 'destroy']);
            Route::get('academia/{academiaVideo}/attachments/{attachmentId}/download', [AdminAcademiaController::class, 'downloadAttachment']);
            Route::get('blog/summary', [AdminBlogController::class, 'summary']);
            Route::get('blog', [AdminBlogController::class, 'index']);
            Route::get('blog/{postId}', [AdminBlogController::class, 'show']);
            Route::get('chatbots/summary', [ChatbotController::class, 'summary']);
            Route::get('chatbots/options', [ChatbotController::class, 'options']);
            Route::get('chatbots', [ChatbotController::class, 'index']);
            Route::get('chatbots/{chatbot}', [ChatbotController::class, 'show']);
            Route::patch('chatbots/{chatbot}/block', [ChatbotController::class, 'updateBlock']);
            Route::get('marketing/dashboard', [MarketingDashboardController::class, 'summary']);
            Route::get('marketing-plans/options', [MarketingPlanController::class, 'options']);
            Route::get('marketing-plans', [MarketingPlanController::class, 'index']);
            Route::post('marketing-plans', [MarketingPlanController::class, 'store']);
            Route::get('marketing-plans/{marketingPlan}', [MarketingPlanController::class, 'show']);
            Route::get('marketing-plans/{marketingPlan}/preview', [MarketingPlanController::class, 'preview']);
            Route::put('marketing-plans/{marketingPlan}', [MarketingPlanController::class, 'update']);
            Route::patch('marketing-plans/{marketingPlan}/status', [MarketingPlanController::class, 'updateStatus']);
            Route::get('marketing-subscriptions/options', [MarketingSubscriptionController::class, 'options']);
            Route::get('marketing-subscriptions', [MarketingSubscriptionController::class, 'index']);
            Route::get('marketing-subscriptions/{marketingPlanSubscription}', [MarketingSubscriptionController::class, 'show']);
            Route::patch('marketing-subscriptions/{marketingPlanSubscription}/status', [MarketingSubscriptionController::class, 'updateStatus']);
            Route::post('marketing-subscriptions/{marketingPlanSubscription}/mark-paid', [MarketingSubscriptionController::class, 'markPaid']);
            Route::get('website-subscriptions/options', [WebsiteSubscriptionController::class, 'options']);
            Route::get('website-subscriptions/integration-options', [WebsiteSubscriptionController::class, 'integrationOptions']);
            Route::get('website-subscriptions', [WebsiteSubscriptionController::class, 'index']);
            Route::post('website-subscriptions', [WebsiteSubscriptionController::class, 'store']);
            Route::get('website-subscriptions/{websiteSubscription}', [WebsiteSubscriptionController::class, 'show']);
            Route::put('website-subscriptions/{websiteSubscription}', [WebsiteSubscriptionController::class, 'update']);
            Route::put('website-subscriptions/{websiteSubscription}/periods/{period}', [WebsiteSubscriptionController::class, 'updatePeriod']);
            Route::post('website-subscriptions/{websiteSubscription}/periods/{period}/mark-paid', [WebsiteSubscriptionController::class, 'markPeriodPaid']);
            Route::get('mercadopago-subscription-plans/options', [MercadoPagoSubscriptionPlanController::class, 'options']);
            Route::get('mercadopago-subscription-plans', [MercadoPagoSubscriptionPlanController::class, 'index']);
            Route::post('mercadopago-subscription-plans', [MercadoPagoSubscriptionPlanController::class, 'store']);
            Route::get('mercadopago-subscription-plans/{mercadopagoSubscriptionPlan}', [MercadoPagoSubscriptionPlanController::class, 'show']);
            Route::put('mercadopago-subscription-plans/{mercadopagoSubscriptionPlan}', [MercadoPagoSubscriptionPlanController::class, 'update']);
            Route::post('mercadopago-subscription-plans/{mercadopagoSubscriptionPlan}/toggle-status', [MercadoPagoSubscriptionPlanController::class, 'toggleStatus']);
            Route::delete('mercadopago-subscription-plans/{mercadopagoSubscriptionPlan}', [MercadoPagoSubscriptionPlanController::class, 'destroy']);
        });

    Route::middleware(['auth:sanctum', 'role:impulsa_emprendedor'])
        ->prefix('emprendedor')
        ->group(function (): void {
            Route::get('menu', [EmprendedorMenuController::class, 'show']);
            Route::get('dashboard/stats', [EmprendedorDashboardController::class, 'stats']);
            Route::get('dashboard/projects/{projectId}/phases', [EmprendedorDashboardController::class, 'projectPhases']);
            Route::get('contracts/{contractId}', [EmprendedorContractController::class, 'show']);
            Route::post('contracts/{contractId}/sign', [EmprendedorContractController::class, 'sign']);
            Route::get('marketing/plans', [EmprendedorMarketingController::class, 'plans']);
            Route::get('marketing/plans/{planId}', [EmprendedorMarketingController::class, 'showPlan']);
            Route::get('marketing/subscriptions', [EmprendedorMarketingController::class, 'subscriptions']);
            Route::post('marketing/subscriptions', [EmprendedorMarketingController::class, 'storeSubscription']);
            Route::get('marketing/subscriptions/{marketingPlanSubscription}/payment-url', [EmprendedorMarketingController::class, 'paymentUrl']);
            Route::get('products/options', [EmprendedorProductController::class, 'options']);
            Route::get('products/summary', [EmprendedorProductController::class, 'summary']);
            Route::get('products/taxonomy', [EmprendedorProductController::class, 'taxonomy']);
            Route::get('products', [EmprendedorProductController::class, 'index']);
            Route::post('products', [EmprendedorProductController::class, 'store']);
            Route::get('products/{apiProduct}', [EmprendedorProductController::class, 'show']);
            Route::put('products/{apiProduct}', [EmprendedorProductController::class, 'update']);
            Route::patch('products/{apiProduct}/status', [EmprendedorProductController::class, 'updateStatus']);
            Route::delete('products/{apiProduct}', [EmprendedorProductController::class, 'destroy']);
            Route::get('products/{apiProduct}/media/{mediaType}', [EmprendedorProductController::class, 'media']);
            Route::get('chatbot', [EmprendedorChatbotController::class, 'show']);
            Route::get('chatbot/avatar', [EmprendedorChatbotController::class, 'avatar']);
            Route::put('chatbot/settings', [EmprendedorChatbotController::class, 'updateSettings']);
            Route::post('chatbot/settings', [EmprendedorChatbotController::class, 'updateSettings']);
            Route::patch('chatbot/status', [EmprendedorChatbotController::class, 'updateStatus']);
            Route::put('chatbot/nodes', [EmprendedorChatbotController::class, 'syncNodes']);
            Route::get('contact-submissions', [PanelContactSubmissionController::class, 'index']);
            Route::get('contact-submissions/{contactSubmission}', [PanelContactSubmissionController::class, 'show']);
            Route::patch('contact-submissions/{contactSubmission}/state', [PanelContactSubmissionController::class, 'updateState']);
            Route::delete('contact-submissions/{contactSubmission}', [PanelContactSubmissionController::class, 'destroy']);
            Route::get('website-subscription', [EmprendedorWebsiteSubscriptionController::class, 'show']);
            Route::get('pagina-web/overview', [EmprendedorPaginaWebController::class, 'overview']);
            Route::get('definicion', [EmprendedorDefinicionController::class, 'show']);
            Route::put('definicion/buyer-persona', [EmprendedorDefinicionController::class, 'saveBuyerPersona']);
            Route::put('definicion/mision', [EmprendedorDefinicionController::class, 'saveMision']);
            Route::put('definicion/vision', [EmprendedorDefinicionController::class, 'saveVision']);
            Route::put('definicion/landing', [EmprendedorDefinicionController::class, 'saveLanding']);
            Route::post('definicion/generate-estructura', [EmprendedorDefinicionController::class, 'generateEstructura'])
                ->middleware('throttle:10,1');
            Route::get('metrics/summary', [EmprendedorMetricsController::class, 'summary']);
            Route::get('metrics/dashboard', [EmprendedorMetricsController::class, 'dashboard']);
            Route::get('finanzas/summary', [EmprendedorFinanzasController::class, 'summary']);
            Route::get('finanzas/settings', [EmprendedorFinanzasController::class, 'settings']);
            Route::put('finanzas/settings', [EmprendedorFinanzasController::class, 'updateSettings']);
            Route::get('finanzas/categories', [EmprendedorFinanzasController::class, 'categories']);
            Route::post('finanzas/categories', [EmprendedorFinanzasController::class, 'storeCategory']);
            Route::get('finanzas/movements', [EmprendedorFinanzasController::class, 'movements']);
            Route::post('finanzas/movements', [EmprendedorFinanzasController::class, 'storeMovement']);
            Route::put('finanzas/movements/{movementId}', [EmprendedorFinanzasController::class, 'updateMovement']);
            Route::delete('finanzas/movements/{movementId}', [EmprendedorFinanzasController::class, 'destroyMovement']);
            Route::get('finanzas/fixed-costs', [EmprendedorFinanzasController::class, 'fixedCosts']);
            Route::post('finanzas/fixed-costs', [EmprendedorFinanzasController::class, 'storeFixedCost']);
            Route::put('finanzas/fixed-costs/{costId}', [EmprendedorFinanzasController::class, 'updateFixedCost']);
            Route::delete('finanzas/fixed-costs/{costId}', [EmprendedorFinanzasController::class, 'destroyFixedCost']);
            Route::get('finanzas/pricing-items', [EmprendedorFinanzasController::class, 'pricingItems']);
            Route::post('finanzas/pricing-items', [EmprendedorFinanzasController::class, 'storePricingItem']);
            Route::put('finanzas/pricing-items/{itemId}', [EmprendedorFinanzasController::class, 'updatePricingItem']);
            Route::delete('finanzas/pricing-items/{itemId}', [EmprendedorFinanzasController::class, 'destroyPricingItem']);
            Route::post('finanzas/pricing/preview', [EmprendedorFinanzasController::class, 'pricingPreview']);
            Route::post('finanzas/break-even/preview', [EmprendedorFinanzasController::class, 'breakEvenPreview']);
            Route::get('finanzas/product-references', [EmprendedorFinanzasController::class, 'productReferences']);
            Route::get('finanzas/projection/baseline', [EmprendedorFinanzasController::class, 'projectionBaseline']);
            Route::post('finanzas/projection/preview', [EmprendedorFinanzasController::class, 'projectionPreview']);
            Route::get('finanzas/projections', [EmprendedorFinanzasController::class, 'projections']);
            Route::post('finanzas/projections', [EmprendedorFinanzasController::class, 'storeProjection']);
            Route::put('finanzas/projections/{projectionId}', [EmprendedorFinanzasController::class, 'updateProjection']);
            Route::delete('finanzas/projections/{projectionId}', [EmprendedorFinanzasController::class, 'destroyProjection']);
            Route::post('finanzas/scenarios/preview', [EmprendedorFinanzasController::class, 'scenarioPreview']);
            Route::post('finanzas/scenarios/compare', [EmprendedorFinanzasController::class, 'compareScenarios']);
            Route::get('finanzas/scenarios', [EmprendedorFinanzasController::class, 'scenarios']);
            Route::post('finanzas/scenarios', [EmprendedorFinanzasController::class, 'storeScenario']);
            Route::put('finanzas/scenarios/{scenarioId}', [EmprendedorFinanzasController::class, 'updateScenario']);
            Route::delete('finanzas/scenarios/{scenarioId}', [EmprendedorFinanzasController::class, 'destroyScenario']);
            Route::get('metas/options', [EmprendedorGoalsController::class, 'options']);
            Route::get('metas', [EmprendedorGoalsController::class, 'index']);
            Route::post('metas', [EmprendedorGoalsController::class, 'store']);
            Route::get('metas/{goalId}', [EmprendedorGoalsController::class, 'show']);
            Route::put('metas/{goalId}', [EmprendedorGoalsController::class, 'update']);
            Route::delete('metas/{goalId}', [EmprendedorGoalsController::class, 'destroy']);
            Route::post('metas/{goalId}/objectives', [EmprendedorGoalsController::class, 'storeObjective']);
            Route::put('metas/{goalId}/objectives/{objectiveId}', [EmprendedorGoalsController::class, 'updateObjective']);
            Route::patch('metas/{goalId}/objectives/{objectiveId}/status', [EmprendedorGoalsController::class, 'updateObjectiveStatus']);
            Route::delete('metas/{goalId}/objectives/{objectiveId}', [EmprendedorGoalsController::class, 'destroyObjective']);
            Route::get('academia/taxonomy', [EmprendedorAcademiaController::class, 'taxonomy']);
            Route::get('academia', [EmprendedorAcademiaController::class, 'index']);
            Route::get('academia/{videoId}', [EmprendedorAcademiaController::class, 'show']);
            Route::get('academia/{videoId}/attachments/{attachmentId}/download', [EmprendedorAcademiaController::class, 'downloadAttachment']);
            Route::get('blog/taxonomy', [EmprendedorBlogController::class, 'taxonomy']);
            Route::get('blog', [EmprendedorBlogController::class, 'index']);
            Route::post('blog', [EmprendedorBlogController::class, 'store']);
            Route::get('blog/{postId}', [EmprendedorBlogController::class, 'show']);
            Route::put('blog/{postId}', [EmprendedorBlogController::class, 'update']);
            Route::patch('blog/{postId}/status', [EmprendedorBlogController::class, 'updateStatus']);
            Route::get('blog/{postId}/media/{mediaType}', [EmprendedorBlogController::class, 'media']);
            Route::delete('blog/{postId}', [EmprendedorBlogController::class, 'destroy']);
        });

    Route::middleware(['auth:sanctum', 'role:impulsa_cliente'])
        ->prefix('cliente')
        ->group(function (): void {
            Route::get('menu', [ClienteMenuController::class, 'show']);
            Route::get('dashboard/stats', [ClienteDashboardController::class, 'stats']);
            Route::get('contracts/{contractId}', [ClienteContractController::class, 'show']);
            Route::post('contracts/{contractId}/sign', [ClienteContractController::class, 'sign']);
            Route::get('marketing/plans', [ClienteMarketingController::class, 'plans']);
            Route::get('marketing/plans/{planId}', [ClienteMarketingController::class, 'showPlan']);
            Route::get('marketing/subscriptions', [ClienteMarketingController::class, 'subscriptions']);
            Route::post('marketing/subscriptions', [ClienteMarketingController::class, 'storeSubscription']);
            Route::get('marketing/subscriptions/{marketingPlanSubscription}/payment-url', [ClienteMarketingController::class, 'paymentUrl']);
            Route::get('products/options', [ClienteProductController::class, 'options']);
            Route::get('products/summary', [ClienteProductController::class, 'summary']);
            Route::get('products/taxonomy', [ClienteProductController::class, 'taxonomy']);
            Route::get('products', [ClienteProductController::class, 'index']);
            Route::post('products', [ClienteProductController::class, 'store']);
            Route::get('products/{apiProduct}', [ClienteProductController::class, 'show']);
            Route::put('products/{apiProduct}', [ClienteProductController::class, 'update']);
            Route::patch('products/{apiProduct}/status', [ClienteProductController::class, 'updateStatus']);
            Route::delete('products/{apiProduct}', [ClienteProductController::class, 'destroy']);
            Route::get('products/{apiProduct}/media/{mediaType}', [ClienteProductController::class, 'media']);
            Route::get('chatbot', [ClienteChatbotController::class, 'show']);
            Route::get('chatbot/avatar', [ClienteChatbotController::class, 'avatar']);
            Route::put('chatbot/settings', [ClienteChatbotController::class, 'updateSettings']);
            Route::post('chatbot/settings', [ClienteChatbotController::class, 'updateSettings']);
            Route::patch('chatbot/status', [ClienteChatbotController::class, 'updateStatus']);
            Route::put('chatbot/nodes', [ClienteChatbotController::class, 'syncNodes']);
            Route::get('contact-submissions', [PanelContactSubmissionController::class, 'index']);
            Route::get('contact-submissions/{contactSubmission}', [PanelContactSubmissionController::class, 'show']);
            Route::patch('contact-submissions/{contactSubmission}/state', [PanelContactSubmissionController::class, 'updateState']);
            Route::delete('contact-submissions/{contactSubmission}', [PanelContactSubmissionController::class, 'destroy']);
            Route::get('metrics/summary', [ClienteMetricsController::class, 'summary']);
            Route::get('metrics/dashboard', [ClienteMetricsController::class, 'dashboard']);
            Route::get('finanzas/summary', [ClienteFinanzasController::class, 'summary']);
            Route::get('finanzas/settings', [ClienteFinanzasController::class, 'settings']);
            Route::put('finanzas/settings', [ClienteFinanzasController::class, 'updateSettings']);
            Route::get('finanzas/categories', [ClienteFinanzasController::class, 'categories']);
            Route::post('finanzas/categories', [ClienteFinanzasController::class, 'storeCategory']);
            Route::get('finanzas/movements', [ClienteFinanzasController::class, 'movements']);
            Route::post('finanzas/movements', [ClienteFinanzasController::class, 'storeMovement']);
            Route::put('finanzas/movements/{movementId}', [ClienteFinanzasController::class, 'updateMovement']);
            Route::delete('finanzas/movements/{movementId}', [ClienteFinanzasController::class, 'destroyMovement']);
            Route::get('finanzas/fixed-costs', [ClienteFinanzasController::class, 'fixedCosts']);
            Route::post('finanzas/fixed-costs', [ClienteFinanzasController::class, 'storeFixedCost']);
            Route::put('finanzas/fixed-costs/{costId}', [ClienteFinanzasController::class, 'updateFixedCost']);
            Route::delete('finanzas/fixed-costs/{costId}', [ClienteFinanzasController::class, 'destroyFixedCost']);
            Route::get('finanzas/pricing-items', [ClienteFinanzasController::class, 'pricingItems']);
            Route::post('finanzas/pricing-items', [ClienteFinanzasController::class, 'storePricingItem']);
            Route::put('finanzas/pricing-items/{itemId}', [ClienteFinanzasController::class, 'updatePricingItem']);
            Route::delete('finanzas/pricing-items/{itemId}', [ClienteFinanzasController::class, 'destroyPricingItem']);
            Route::post('finanzas/pricing/preview', [ClienteFinanzasController::class, 'pricingPreview']);
            Route::post('finanzas/break-even/preview', [ClienteFinanzasController::class, 'breakEvenPreview']);
            Route::get('finanzas/product-references', [ClienteFinanzasController::class, 'productReferences']);
            Route::get('finanzas/projection/baseline', [ClienteFinanzasController::class, 'projectionBaseline']);
            Route::post('finanzas/projection/preview', [ClienteFinanzasController::class, 'projectionPreview']);
            Route::get('finanzas/projections', [ClienteFinanzasController::class, 'projections']);
            Route::post('finanzas/projections', [ClienteFinanzasController::class, 'storeProjection']);
            Route::put('finanzas/projections/{projectionId}', [ClienteFinanzasController::class, 'updateProjection']);
            Route::delete('finanzas/projections/{projectionId}', [ClienteFinanzasController::class, 'destroyProjection']);
            Route::post('finanzas/scenarios/preview', [ClienteFinanzasController::class, 'scenarioPreview']);
            Route::post('finanzas/scenarios/compare', [ClienteFinanzasController::class, 'compareScenarios']);
            Route::get('finanzas/scenarios', [ClienteFinanzasController::class, 'scenarios']);
            Route::post('finanzas/scenarios', [ClienteFinanzasController::class, 'storeScenario']);
            Route::put('finanzas/scenarios/{scenarioId}', [ClienteFinanzasController::class, 'updateScenario']);
            Route::delete('finanzas/scenarios/{scenarioId}', [ClienteFinanzasController::class, 'destroyScenario']);
            Route::get('metas/options', [ClienteGoalsController::class, 'options']);
            Route::get('metas', [ClienteGoalsController::class, 'index']);
            Route::post('metas', [ClienteGoalsController::class, 'store']);
            Route::get('metas/{goalId}', [ClienteGoalsController::class, 'show']);
            Route::put('metas/{goalId}', [ClienteGoalsController::class, 'update']);
            Route::delete('metas/{goalId}', [ClienteGoalsController::class, 'destroy']);
            Route::post('metas/{goalId}/objectives', [ClienteGoalsController::class, 'storeObjective']);
            Route::put('metas/{goalId}/objectives/{objectiveId}', [ClienteGoalsController::class, 'updateObjective']);
            Route::patch('metas/{goalId}/objectives/{objectiveId}/status', [ClienteGoalsController::class, 'updateObjectiveStatus']);
            Route::delete('metas/{goalId}/objectives/{objectiveId}', [ClienteGoalsController::class, 'destroyObjective']);
            Route::get('academia/taxonomy', [ClienteAcademiaController::class, 'taxonomy']);
            Route::get('academia', [ClienteAcademiaController::class, 'index']);
            Route::get('academia/{videoId}', [ClienteAcademiaController::class, 'show']);
            Route::get('academia/{videoId}/attachments/{attachmentId}/download', [ClienteAcademiaController::class, 'downloadAttachment']);
            Route::get('blog/taxonomy', [ClienteBlogController::class, 'taxonomy']);
            Route::get('blog', [ClienteBlogController::class, 'index']);
            Route::post('blog', [ClienteBlogController::class, 'store']);
            Route::get('blog/{postId}', [ClienteBlogController::class, 'show']);
            Route::put('blog/{postId}', [ClienteBlogController::class, 'update']);
            Route::patch('blog/{postId}/status', [ClienteBlogController::class, 'updateStatus']);
            Route::get('blog/{postId}/media/{mediaType}', [ClienteBlogController::class, 'media']);
            Route::delete('blog/{postId}', [ClienteBlogController::class, 'destroy']);
        });

    Route::middleware(['auth:sanctum', 'role:impulsa_marketing'])
        ->prefix('marketing-user')
        ->group(function (): void {
            Route::get('menu', [MarketingUserMenuController::class, 'show']);
            Route::get('dashboard', [MarketingUserDashboardController::class, 'summary']);
            Route::get('marketing-plans/options', [MarketingUserPlanController::class, 'options']);
            Route::get('marketing-plans', [MarketingUserPlanController::class, 'index']);
            Route::post('marketing-plans', [MarketingUserPlanController::class, 'store']);
            Route::get('marketing-plans/{marketingPlan}', [MarketingUserPlanController::class, 'show']);
            Route::get('marketing-plans/{marketingPlan}/preview', [MarketingUserPlanController::class, 'preview']);
            Route::put('marketing-plans/{marketingPlan}', [MarketingUserPlanController::class, 'update']);
            Route::patch('marketing-plans/{marketingPlan}/status', [MarketingUserPlanController::class, 'updateStatus']);
            Route::get('marketing-subscriptions/options', [MarketingUserSubscriptionController::class, 'options']);
            Route::get('marketing-subscriptions', [MarketingUserSubscriptionController::class, 'index']);
            Route::get('marketing-subscriptions/{marketingPlanSubscription}', [MarketingUserSubscriptionController::class, 'show']);
            Route::patch('marketing-subscriptions/{marketingPlanSubscription}/status', [MarketingUserSubscriptionController::class, 'updateStatus']);
            Route::post('marketing-subscriptions/{marketingPlanSubscription}/mark-paid', [MarketingUserSubscriptionController::class, 'markPaid']);
            Route::get('monitor/campaigns', [MarketingUserMonitorController::class, 'campaigns']);
            Route::post('monitor/import-csv', [MarketingUserMonitorController::class, 'importCsv']);
            Route::get('results', [MarketingUserResultsController::class, 'index']);
            Route::get('users', [MarketingUserUsersController::class, 'index']);
        });

    Route::middleware(['auth:sanctum', 'role:impulsa_colaborador'])
        ->prefix('colaborador')
        ->group(function (): void {
            Route::get('menu', [ColaboradorMenuController::class, 'show']);
            Route::get('projects/options', [ColaboradorProjectController::class, 'options']);
            Route::get('projects', [ColaboradorProjectController::class, 'index']);
            Route::get('projects/{project}', [ColaboradorProjectController::class, 'show']);
            Route::patch('projects/{project}/status', [ColaboradorProjectController::class, 'updateStatus']);
            Route::patch('projects/{project}/phases/{phase}/status', [ColaboradorProjectController::class, 'updatePhaseStatus']);
            Route::patch('projects/{project}/deliverables/{deliverable}/status', [ColaboradorProjectController::class, 'updateDeliverableStatus']);
            Route::get('projects/{project}/comments', [ColaboradorProjectController::class, 'projectComments']);
            Route::get('projects/{project}/deliverables/{deliverable}/comments', [ColaboradorProjectController::class, 'comments']);
            Route::post('projects/{project}/deliverables/{deliverable}/comments', [ColaboradorProjectController::class, 'storeComment']);
            Route::post('projects/{project}/deliverables/{deliverable}/comments/read', [ColaboradorProjectController::class, 'markCommentsRead']);
            Route::post('projects/{project}/phases/{phase}/attachments', [ColaboradorProjectController::class, 'storePhaseAttachment']);
            Route::post('projects/{project}/deliverables/{deliverable}/attachments', [ColaboradorProjectController::class, 'storeDeliverableAttachment']);
            Route::get('projects/{project}/attachments/{attachment}/file', [ColaboradorProjectController::class, 'showAttachment']);
            Route::delete('projects/{project}/attachments/{attachment}', [ColaboradorProjectController::class, 'destroyAttachment']);
        });
});
