CREATE TABLE `api_blog_posts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `api_integration_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(180) NOT NULL,
  `slug` VARCHAR(220) NOT NULL,
  `subtitle` VARCHAR(255) DEFAULT NULL,
  `author` VARCHAR(180) DEFAULT NULL,
  `bibliography` TEXT DEFAULT NULL,
  `cover_image_path` VARCHAR(255) DEFAULT NULL,
  `attachment_path` VARCHAR(255) DEFAULT NULL,
  `category` VARCHAR(120) DEFAULT NULL,
  `subcategory` VARCHAR(120) DEFAULT NULL,
  `excerpt` VARCHAR(300) DEFAULT NULL,
  `description_html` LONGTEXT NOT NULL,
  `publication_date` DATETIME DEFAULT NULL,
  `status` ENUM('active','inactive','draft') NOT NULL DEFAULT 'draft',
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 1,
  `metadata_json` LONGTEXT DEFAULT NULL,
  `created_by_user_id` INT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_api_blog_posts_integration_slug` (`api_integration_id`, `slug`),
  KEY `idx_api_blog_posts_integration_status` (`api_integration_id`, `status`),
  KEY `idx_api_blog_posts_publication_date` (`publication_date`),
  KEY `idx_api_blog_posts_created_at` (`created_at`),
  KEY `idx_api_blog_posts_updated_at` (`updated_at`),
  CONSTRAINT `fk_api_blog_posts_integration`
    FOREIGN KEY (`api_integration_id`) REFERENCES `api_integrations` (`id`),
  CONSTRAINT `fk_api_blog_posts_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `user_auth` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `api_products` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `api_integration_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(180) NOT NULL,
  `slug` VARCHAR(220) NOT NULL,
  `sku` VARCHAR(80) DEFAULT NULL,
  `short_description` VARCHAR(300) DEFAULT NULL,
  `description_html` LONGTEXT NOT NULL,
  `main_image_path` VARCHAR(255) DEFAULT NULL,
  `thumbnail_path` VARCHAR(255) DEFAULT NULL,
  `attachment_path` VARCHAR(255) DEFAULT NULL,
  `category` VARCHAR(120) DEFAULT NULL,
  `subcategory` VARCHAR(120) DEFAULT NULL,
  `price` DECIMAL(12,2) DEFAULT NULL,
  `compare_at_price` DECIMAL(12,2) DEFAULT NULL,
  `currency` VARCHAR(8) NOT NULL DEFAULT 'ARS',
  `stock_quantity` INT DEFAULT NULL,
  `availability` ENUM('in_stock','out_of_stock','preorder','on_request') NOT NULL DEFAULT 'on_request',
  `status` ENUM('active','inactive','draft') NOT NULL DEFAULT 'draft',
  `featured` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 1,
  `metadata_json` LONGTEXT DEFAULT NULL,
  `created_by_user_id` INT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_api_products_integration_slug` (`api_integration_id`, `slug`),
  KEY `idx_api_products_integration_status` (`api_integration_id`, `status`),
  KEY `idx_api_products_sku` (`sku`),
  KEY `idx_api_products_created_at` (`created_at`),
  KEY `idx_api_products_updated_at` (`updated_at`),
  CONSTRAINT `fk_api_products_integration`
    FOREIGN KEY (`api_integration_id`) REFERENCES `api_integrations` (`id`),
  CONSTRAINT `fk_api_products_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `user_auth` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
